### ISSUE TITLE
Use systemd user services for X

### ISSUE THREAD

**Issue by ayekat** [ayekat/dotfiles#2]
It remains to be seen at what point this is usable, but the current xinitrc has clearly become unmaintainable.

**Comment by roosemberth** [comment]
FWIW, I use sddm and symlinked my xinitrc to .xsession, woks great and I don't have to login and exec

https://github.com/roosemberth/dotfiles/blob/ef1fabc25b9c583ab5c9a0571add56e0b22c6327/nixos-config/machines/Triglav.nix#L86-L89

**Comment by ayekat** [comment]
Closing this as wontfix, because this is a little silly IMHO. Should better spend time pushing karuiwm forward to the point where we can start using Wayland.
