### ISSUE TITLE
etc/X11/Xresources hardcodes home directory path

### ISSUE THREAD

**Issue by ayekat** [ayekat/dotfiles#21]
On line 92:

    URxvt.perl-lib       : /home/ayekat/.local/lib/urxvt/perl/

We'll have to see if it is possible to use environment variables there. This is quite a bit annoying if using the dotfiles for some other user.

**Comment by marcthe12** [comment]
It depend on the evacation of xrdb. xrdb use the c prprosesor. So can use c Macros, includes.

**Comment by ayekat** [comment]
Thanks a lot for the hint! I now use `XDG_...` environment variables for this.
