### ISSUE TITLE
What happened to karuibar

### ISSUE THREAD

**Issue by su8** [ayekat/dotfiles#25]
Hello @ayekat 

What happened to karuibar ?

Can you give me a tarball with all commits and the program itself ?

Regards,

su8

**Comment by ayekat** [comment]
Hello

Sorry and wow, I hadn't even thought of the possibility that anyone (except me) might be using karuibar...

I've moved it to GitLab along with most of my other projects a few months ago. It is now available under https://gitlab.com/ayekat/karuibar.

**EDIT**: I noticed you've got your own status bar, so I'm relieved to learn you're not actually using it, but probably rather just as a reference. ^^

**Comment by su8** [comment]
Thanks ♥
