### ISSUE TITLE
Qt/KDE saving their state into their configuration files

### ISSUE THREAD

**Issue by Thaodan** [ayekat/dotfiles#43]
I noticed you use some Qt/KDE apps, this might help you to keep track:
https://bugs.kde.org/show_bug.cgi?id=397602

**Comment by ayekat** [comment]
Hi, thanks for the link!

As I can't really do anything about that in the context of this repo (apart from pushing upstream towards splitting state and config), I guess it's better to just add a comment to #7 with that link if you want, so it's tracked somewhere. :slightly_smiling_face: 

Closing this one here for now.
